export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'cashier' | 'senior_cashier' | 'manager' | 'owner' | 'admin';
export type ItemCondition = 'Mint' | 'Excellent' | 'Good' | 'Fair' | 'Damaged';
export type ItemStatus = 'Vault Hold' | 'Retail Floor' | 'Sold' | 'Redeemed' | 'Reserved' | 'Flagged' | 'InStock' | 'Forfeited' | 'Pending Forfeit' | 'Returned' | 'Reversed';
export type LoanStatus = 'Active' | 'Extended' | 'Redeemed' | 'Forfeited' | 'Archived' | 'Pending Forfeit';

export interface Database {
  public: {
    Tables: {
      refund_requests: {
        Row: {
          id: string;
          shop_id: string;
          sale_id: string | null;
          receipt_number: string;
          item_id: string;
          item_sku: string;
          item_title: string;
          quantity: number;
          refund_amount: number;
          reason: string;
          status: string;
          requested_by: string | null;
          requested_by_name: string;
          approved_by: string | null;
          approved_by_name: string | null;
          rejection_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id: string;
          sale_id?: string | null;
          receipt_number: string;
          item_id: string;
          item_sku: string;
          item_title: string;
          quantity?: number;
          refund_amount: number;
          reason: string;
          status?: string;
          requested_by?: string | null;
          requested_by_name: string;
          approved_by?: string | null;
          approved_by_name?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string;
          sale_id?: string | null;
          receipt_number?: string;
          item_id?: string;
          item_sku?: string;
          item_title?: string;
          quantity?: number;
          refund_amount?: number;
          reason?: string;
          status?: string;
          requested_by?: string | null;
          requested_by_name?: string;
          approved_by?: string | null;
          approved_by_name?: string | null;
          rejection_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      shop_profiles: {
        Row: {
          id: string;
          shop_code: string;
          shop_name: string;
          trading_name: string | null;
          registration_number: string | null;
          vat_number: string | null;
          saps_dealer_license: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          city: string | null;
          province: string | null;
          postal_code: string | null;
          currency: string;
          receipt_header: string | null;
          receipt_footer: string | null;
          is_active: boolean;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_code: string;
          shop_name: string;
          trading_name?: string | null;
          registration_number?: string | null;
          vat_number?: string | null;
          saps_dealer_license?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          postal_code?: string | null;
          currency?: string;
          receipt_header?: string | null;
          receipt_footer?: string | null;
          is_active?: boolean;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_code?: string;
          shop_name?: string;
          trading_name?: string | null;
          registration_number?: string | null;
          vat_number?: string | null;
          saps_dealer_license?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          province?: string | null;
          postal_code?: string | null;
          currency?: string;
          receipt_header?: string | null;
          receipt_footer?: string | null;
          is_active?: boolean;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          shop_id: string | null;
          email: string | null;
          full_name: string;
          cashier_code: string;
          role: UserRole;
          phone: string | null;
          avatar_url: string | null;
          pin_code: string | null;
          pin_hash: string | null;
          digital_signature: string | null;
          schedule: Json;
          permissions: Json;
          is_active: boolean;
          last_sign_in_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          shop_id?: string | null;
          email?: string | null;
          full_name: string;
          cashier_code?: string;
          role?: UserRole;
          phone?: string | null;
          avatar_url?: string | null;
          pin_code?: string | null;
          pin_hash?: string | null;
          digital_signature?: string | null;
          schedule?: Json;
          permissions?: Json;
          is_active?: boolean;
          last_sign_in_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          email?: string | null;
          full_name?: string;
          cashier_code?: string;
          role?: UserRole;
          phone?: string | null;
          avatar_url?: string | null;
          pin_code?: string | null;
          pin_hash?: string | null;
          digital_signature?: string | null;
          schedule?: Json;
          permissions?: Json;
          is_active?: boolean;
          last_sign_in_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      shop_items: {
        Row: {
          id: string;
          shop_id: string | null;
          sku: string;
          title: string;
          category: string;
          serial_or_imei: string | null;
          condition: ItemCondition;
          acquisition_type: string;
          cost_basis: number;
          retail_price: number;
          vault_location: string | null;
          status: ItemStatus;
          days_in_vault: number;
          image_url: string | null;
          storage_key: string | null;
          specs: string | null;
          pawn_ticket_id: string | null;
          brand?: string | null;
          model?: string | null;
          stock_location?: string | null;
          source_type?: string | null;
          source_status?: string | null;
          source_note?: string | null;
          internal_note?: string | null;
          created_by: string | null;
          added_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          sku: string;
          title: string;
          category: string;
          serial_or_imei?: string | null;
          condition?: ItemCondition;
          acquisition_type?: string;
          cost_basis?: number;
          retail_price?: number;
          vault_location?: string | null;
          status?: ItemStatus;
          days_in_vault?: number;
          image_url?: string | null;
          storage_key?: string | null;
          specs?: string | null;
          pawn_ticket_id?: string | null;
          brand?: string | null;
          model?: string | null;
          stock_location?: string | null;
          source_type?: string | null;
          source_status?: string | null;
          source_note?: string | null;
          internal_note?: string | null;
          created_by?: string | null;
          added_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          sku?: string;
          title?: string;
          category?: string;
          serial_or_imei?: string | null;
          condition?: ItemCondition;
          acquisition_type?: string;
          cost_basis?: number;
          retail_price?: number;
          vault_location?: string | null;
          status?: ItemStatus;
          days_in_vault?: number;
          image_url?: string | null;
          storage_key?: string | null;
          specs?: string | null;
          pawn_ticket_id?: string | null;
          brand?: string | null;
          model?: string | null;
          stock_location?: string | null;
          source_type?: string | null;
          source_status?: string | null;
          source_note?: string | null;
          internal_note?: string | null;
          created_by?: string | null;
          added_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          shop_id: string | null;
          full_name: string;
          id_type: string;
          id_number: string;
          mobile: string;
          address: string | null;
          dob: string | null;
          gender: string | null;
          verified: boolean;
          is_flagged: boolean;
          last_communication_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          full_name: string;
          id_type?: string;
          id_number: string;
          mobile: string;
          address?: string | null;
          dob?: string | null;
          gender?: string | null;
          verified?: boolean;
          is_flagged?: boolean;
          last_communication_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          full_name?: string;
          id_type?: string;
          id_number?: string;
          mobile?: string;
          address?: string | null;
          dob?: string | null;
          gender?: string | null;
          verified?: boolean;
          is_flagged?: boolean;
          last_communication_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      sellers: {
        Row: {
          id: string;
          shop_id: string | null;
          full_name: string;
          id_type: string;
          id_number: string;
          mobile: string;
          email: string | null;
          address: string | null;
          verified: boolean;
          verification_status: string;
          verification_method: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          full_name: string;
          id_type?: string;
          id_number: string;
          mobile: string;
          email?: string | null;
          address?: string | null;
          verified?: boolean;
          verification_status?: string;
          verification_method?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          full_name?: string;
          id_type?: string;
          id_number?: string;
          mobile?: string;
          email?: string | null;
          address?: string | null;
          verified?: boolean;
          verification_status?: string;
          verification_method?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      seller_transactions: {
        Row: {
          id: string;
          shop_id: string | null;
          transaction_number: string | null;
          seller_id: string;
          item_id: string | null;
          item_sku: string | null;
          item_title: string | null;
          transaction_type: string;
          amount_paid: number;
          total_proposed_payout: number;
          total_approved_payout: number;
          payment_method: string | null;
          payment_status: string;
          transaction_status: string;
          compliance_status: string;
          sku: string | null;
          asset_tag: string | null;
          compliance_reference: string | null;
          saps_reference: string | null;
          cashier_id: string | null;
          status: string;
          metadata: Json;
          timestamp: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          transaction_number?: string | null;
          seller_id: string;
          item_id?: string | null;
          item_sku?: string | null;
          item_title?: string | null;
          transaction_type?: string;
          amount_paid: number;
          total_proposed_payout?: number;
          total_approved_payout?: number;
          payment_method?: string | null;
          payment_status?: string;
          transaction_status?: string;
          compliance_status?: string;
          sku?: string | null;
          asset_tag?: string | null;
          compliance_reference?: string | null;
          saps_reference?: string | null;
          cashier_id?: string | null;
          status?: string;
          metadata?: Json;
          timestamp?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          transaction_number?: string | null;
          seller_id?: string;
          item_id?: string | null;
          item_sku?: string | null;
          item_title?: string | null;
          transaction_type?: string;
          amount_paid?: number;
          total_proposed_payout?: number;
          total_approved_payout?: number;
          payment_method?: string | null;
          payment_status?: string;
          transaction_status?: string;
          compliance_status?: string;
          sku?: string | null;
          asset_tag?: string | null;
          compliance_reference?: string | null;
          saps_reference?: string | null;
          cashier_id?: string | null;
          status?: string;
          metadata?: Json;
          timestamp?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      seller_transaction_items: {
        Row: {
          id: string;
          seller_transaction_id: string;
          shop_id: string;
          item_id: string;
          item_sku: string;
          item_title: string;
          amount_paid: number;
          retail_price: number;
          serial_or_imei: string | null;
          condition: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          seller_transaction_id: string;
          shop_id: string;
          item_id: string;
          item_sku: string;
          item_title: string;
          amount_paid?: number;
          retail_price?: number;
          serial_or_imei?: string | null;
          condition?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          seller_transaction_id?: string;
          shop_id?: string;
          item_id?: string;
          item_sku?: string;
          item_title?: string;
          amount_paid?: number;
          retail_price?: number;
          serial_or_imei?: string | null;
          condition?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      seller_reversals: {
        Row: {
          id: string;
          shop_id: string;
          seller_transaction_id: string;
          item_id: string;
          seller_id: string;
          original_payout: number;
          reversal_amount: number;
          reason: string;
          requested_by: string | null;
          approved_by: string | null;
          status: string;
          resulting_inventory_status: string | null;
          resulting_payment_status: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id: string;
          seller_transaction_id: string;
          item_id: string;
          seller_id: string;
          original_payout?: number;
          reversal_amount?: number;
          reason: string;
          requested_by?: string | null;
          approved_by?: string | null;
          status?: string;
          resulting_inventory_status?: string | null;
          resulting_payment_status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string;
          seller_transaction_id?: string;
          item_id?: string;
          seller_id?: string;
          original_payout?: number;
          reversal_amount?: number;
          reason?: string;
          requested_by?: string | null;
          approved_by?: string | null;
          status?: string;
          resulting_inventory_status?: string | null;
          resulting_payment_status?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      terminal_sessions: {
        Row: {
          id: string;
          user_id: string;
          shop_id: string;
          terminal_id: string;
          terminal_name: string | null;
          status: string;
          activated_at: string;
          last_heartbeat_at: string;
          invalidated_at: string | null;
          invalidation_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          shop_id: string;
          terminal_id: string;
          terminal_name?: string | null;
          status?: string;
          activated_at?: string;
          last_heartbeat_at?: string;
          invalidated_at?: string | null;
          invalidation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          shop_id?: string;
          terminal_id?: string;
          terminal_name?: string | null;
          status?: string;
          activated_at?: string;
          last_heartbeat_at?: string;
          invalidated_at?: string | null;
          invalidation_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      pawn_loans: {
        Row: {
          id: string;
          shop_id: string | null;
          ticket_number: string;
          customer_id: string;
          customer_name: string | null;
          customer_id_number: string | null;
          customer_mobile: string | null;
          customer_address: string | null;
          item_id: string | null;
          item_title: string | null;
          item_category: string | null;
          serial_or_imei: string | null;
          condition: string | null;
          item_image_url: string | null;
          principal: number;
          ncr_monthly_rate: number;
          monthly_interest: number;
          monthly_storage_admin_fee: number;
          total_redemption_amount: number;
          extension_fee: number;
          start_date: string;
          expiry_date: string;
          days_remaining: number;
          days_elapsed: number;
          vault_shelf: string | null;
          status: LoanStatus;
          qr_token: string | null;
          history: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          ticket_number: string;
          customer_id: string;
          customer_name?: string | null;
          customer_id_number?: string | null;
          customer_mobile?: string | null;
          customer_address?: string | null;
          item_id?: string | null;
          item_title?: string | null;
          item_category?: string | null;
          serial_or_imei?: string | null;
          condition?: string | null;
          item_image_url?: string | null;
          principal: number;
          ncr_monthly_rate?: number;
          monthly_interest?: number;
          monthly_storage_admin_fee?: number;
          total_redemption_amount?: number;
          extension_fee?: number;
          start_date: string;
          expiry_date: string;
          days_remaining?: number;
          days_elapsed?: number;
          vault_shelf?: string | null;
          status?: LoanStatus;
          qr_token?: string | null;
          history?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          ticket_number?: string;
          customer_id?: string;
          customer_name?: string | null;
          customer_id_number?: string | null;
          customer_mobile?: string | null;
          customer_address?: string | null;
          item_id?: string | null;
          item_title?: string | null;
          item_category?: string | null;
          serial_or_imei?: string | null;
          condition?: string | null;
          item_image_url?: string | null;
          principal?: number;
          ncr_monthly_rate?: number;
          monthly_interest?: number;
          monthly_storage_admin_fee?: number;
          total_redemption_amount?: number;
          extension_fee?: number;
          start_date?: string;
          expiry_date?: string;
          days_remaining?: number;
          days_elapsed?: number;
          vault_shelf?: string | null;
          status?: LoanStatus;
          qr_token?: string | null;
          history?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      sales: {
        Row: {
          id: string;
          shop_id: string | null;
          receipt_number: string;
          timestamp: string;
          items: Json;
          subtotal: number;
          vat_amount: number;
          total: number;
          tender_method: string;
          amount_tendered: number;
          change: number;
          receipt_type: string;
          customer_mobile: string | null;
          cashier: string;
          status: string;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          receipt_number: string;
          timestamp?: string;
          items: Json;
          subtotal: number;
          vat_amount?: number;
          total: number;
          tender_method: string;
          amount_tendered?: number;
          change?: number;
          receipt_type?: string;
          customer_mobile?: string | null;
          cashier: string;
          status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          receipt_number?: string;
          timestamp?: string;
          items?: Json;
          subtotal?: number;
          vat_amount?: number;
          total?: number;
          tender_method?: string;
          amount_tendered?: number;
          change?: number;
          receipt_type?: string;
          customer_mobile?: string | null;
          cashier?: string;
          status?: string;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      saps_entries: {
        Row: {
          id: string;
          shop_id: string | null;
          entry_number: string;
          timestamp: string;
          customer_id: string;
          customer_name: string;
          customer_id_number: string;
          customer_address: string | null;
          customer_phone: string | null;
          item_description: string;
          category: string | null;
          serial_or_imei: string | null;
          condition: string | null;
          acquisition_type: string;
          consideration_paid: number;
          officer_name: string | null;
          police_station_ref: string | null;
          verification_status: string;
          barcode_ref: string | null;
          is_cancelled: boolean;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          entry_number: string;
          timestamp?: string;
          customer_id: string;
          customer_name: string;
          customer_id_number: string;
          customer_address?: string | null;
          customer_phone?: string | null;
          item_description: string;
          category?: string | null;
          serial_or_imei?: string | null;
          condition?: string | null;
          acquisition_type: string;
          consideration_paid: number;
          officer_name?: string | null;
          police_station_ref?: string | null;
          verification_status?: string;
          barcode_ref?: string | null;
          is_cancelled?: boolean;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          entry_number?: string;
          timestamp?: string;
          customer_id?: string;
          customer_name?: string;
          customer_id_number?: string;
          customer_address?: string | null;
          customer_phone?: string | null;
          item_description?: string;
          category?: string | null;
          serial_or_imei?: string | null;
          condition?: string | null;
          acquisition_type?: string;
          consideration_paid?: number;
          officer_name?: string | null;
          police_station_ref?: string | null;
          verification_status?: string;
          barcode_ref?: string | null;
          is_cancelled?: boolean;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      system_logs: {
        Row: {
          id: string;
          shop_id: string | null;
          event_type: string;
          severity: string;
          actor_id: string | null;
          actor_name: string;
          details: Json;
          saps_reference: string | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          shop_id?: string | null;
          event_type: string;
          severity?: string;
          actor_id?: string | null;
          actor_name: string;
          details?: Json;
          saps_reference?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string | null;
          event_type?: string;
          severity?: string;
          actor_id?: string | null;
          actor_name?: string;
          details?: Json;
          saps_reference?: string | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
    };
  };
}

export type ShopProfileRow = Database['public']['Tables']['shop_profiles']['Row'];
export type ProfileRow = Database['public']['Tables']['profiles']['Row'];
export type ShopItemRow = Database['public']['Tables']['shop_items']['Row'];
export type CustomerRow = Database['public']['Tables']['customers']['Row'];
export type SellerRow = Database['public']['Tables']['sellers']['Row'];
export type SellerTransactionRow = Database['public']['Tables']['seller_transactions']['Row'];
export type SellerTransactionItemRow = Database['public']['Tables']['seller_transaction_items']['Row'];
export type SellerReversalRow = Database['public']['Tables']['seller_reversals']['Row'];
export type TerminalSessionRow = Database['public']['Tables']['terminal_sessions']['Row'];
export type PawnLoanRow = Database['public']['Tables']['pawn_loans']['Row'];
export type SaleRow = Database['public']['Tables']['sales']['Row'];
export type RefundRequestRow = Database['public']['Tables']['refund_requests']['Row'];
export type SapsEntryRow = Database['public']['Tables']['saps_entries']['Row'];
export type SystemLogRow = Database['public']['Tables']['system_logs']['Row'];
